### ISSUE TITLE
Vimeo - return ID not working if `www.` is included in the string.

### ISSUE THREAD

**Issue by ccurtin** [radiovisual/get-video-id#11]
`https://www.vimeo.com/187191771` will return an ID of `undefined`
`https://vimeo.com/187191771` will return the correct ID.

Is there any specific reasoning behind this? Perhaps a regex can be implemented, ie: find `www` and remove it? Or maybe support can be added to include finding URLs structured with `www`?

**Comment by radiovisual** [comment]
There is no reason for this other than the fact that vimeo doesn't serve their traffic or generate urls for sharing/embedding using the `www` prefix, so it's not common to need to extract a vimeo id from a url containing `www`. Vimeo will remove the `www` from the url if you try to visit that link, but I am happy to add in a rule to look for these cases.

**Comment by radiovisual** [comment]
Ok, so as of https://github.com/radiovisual/get-video-id/commit/19a954eb4a99a3cbe6a0beec45df8a52daaa58a2 (`2.1.5`), this module should now find vimeo urls containing `www`. 👍
