### ISSUE TITLE
Loom is missing is NPM package

### ISSUE THREAD

**Issue by clementprevot** [radiovisual/get-video-id#120]
**Describe the bug**  

I'm not sure if I'm missing something or else, but when I compare the code in this repository and the code that is actually shipped in NPM, the Loom part is missing from the main `getVideoId` function.  
We can see "loom" in the types of the expected return, but [this part](https://github.com/radiovisual/get-video-id/blob/master/src/index.js#L65) is missing (as you can see in the screenshot below)

![image](https://github.com/radiovisual/get-video-id/assets/6450505/5a1bab52-6fc8-4b29-adad-0efca8fb1288)

And I do have the latest 4.1.5 version

![image](https://github.com/radiovisual/get-video-id/assets/6450505/0b0830e6-b325-4c76-a267-51924687814c)

**To Reproduce**

- Install through NPM
- Pass a Loom URL
- Get `service` as `undefined`

- Check the code of the installed package in `node_modules`
- See that the loom part is missing in the exported code

**Expected behavior**  

Library should process Loom URLs properly

**Environment**  

- ESM import
- In Next.JS application

**Module version**  

4.1.5

**Comment by radiovisual** [comment]
Yup, you are right! Somehow this is not in the latest version of `4.1.5` 🤔 . Thanks for reporting! I can fix this later on unless someone gets to a PR before me.

**Comment by radiovisual** [comment]
This problem is officially fixed in version `4.1.7`. Thanks for reporting!

**Comment by clementprevot** [comment]
Thanks a lot!
