### ISSUE TITLE
Add Vimeo channel/groups/album url patterns? :)

### ISSUE THREAD

**Issue by jsg2021** [radiovisual/get-video-id#13]
First of all, nice library! 
I started playing with it and noticed these vimeo urls don't seem to work:
```js
`//vimeo.com/channels/${ID}`,
`//vimeo.com/channels/yourchannel/${ID}`,
`//vimeo.com/groups/name/videos/${ID}`,
`//vimeo.com/album/${ALBUM_ID}/video/${ID}`,
```

**Comment by radiovisual** [comment]
@jsg2021, thanks for reporting! I will take a look.  

Do you have working links to these urls that I can use to test with?

**Comment by radiovisual** [comment]
Thanks for reporting. I have fixed this issue via https://github.com/radiovisual/get-video-id/commit/ba46365fb865207dcb76d7dcb9f9dd3afce1f3af. 👍

**Comment by jsg2021** [comment]
awesome!
