### ISSUE TITLE
Cannot get Vimeo attributes

### ISSUE THREAD

**Issue by moogaloop** [radiovisual/get-video-id#16]
Vimeo attributes are not successfully parsed using the URL format: https://vimeo.com/moogaloop.swf?clip_id=[videoID]

**Comment by radiovisual** [comment]
Can you send me an example of a working link? And tell me where this url pattern comes from? When I try to use it, I just get forwarded to the video page that is associated with the video id.

**Comment by moogaloop** [comment]
Here is a sample link: http://vimeo.com/moogaloop.swf?clip_id=10551932&server=vimeo.com&show_title=0&show_byline=0&show_portrait=0&color=00adef&fullscreen=1
I got this from our database (old legacy site, using the old embed code)

**Comment by radiovisual** [comment]
This will get fixed with PR #17 👍 

Thanks for reporting.

**Comment by radiovisual** [comment]
Fixed in `v3.1.0`

👍
