### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by kaganjd** [radiovisual/get-video-id#2]
`$ npm install get-video-id` installs version 0.0.6 even though 1.0.0 is the latest release.

`$ npm install get-video-id@latest` does install version 1.0.0.

**Comment by kaganjd** [comment]
Oops, my mistake. This happened because I specified in my packages.json file that I wanted version 0.0.6. When I changed the version in packages.json, I got the correct version from npm. Feel free to close!

**Comment by radiovisual** [comment]
No problem at all! Thanks!
