### ISSUE TITLE
vimeo urls return undefined when time query in url

### ISSUE THREAD

**Issue by meandavejustice** [radiovisual/get-video-id#3]
```
> getVideoId = require('get-video-id');
[Function]
> getVideoId('https://vimeo.com/140542479#t=0m3s')
undefined
> getVideoId('https://vimeo.com/140542479')
'140542479'
> 
```

**Comment by radiovisual** [comment]
Thanks for this. I have closed this issue via https://github.com/radiovisual/get-video-id/commit/890792be8c0092c9b8b47202896188404e3daf44. I added your test snippet to the unit tests, and all is passing now. Please let me know if you have any other issues. 👍
