### ISSUE TITLE
vimeo urls with a slash between 2 codes don't seem to work

### ISSUE THREAD

**Issue by amcc** [radiovisual/get-video-id#33]
Some Vimeo URLs are watchable, but don't have a share button (i think they're intended to be locked). However, they should be viewable. Here is an example:
https://vimeo.com/298164563/f9ccc8f6ac

The script returns "Missing YouTube or Vimeo URL", I think the slash confuses it, but i haven't looked closely yet.

I can embed this on other websites. I'm converting a Drupal site to react right now and found this issue - the drupal module embeds it and changes the URL like so: https://player.vimeo.com/video/298164563 - its the same video and this URL works with get-video-id

**Comment by radiovisual** [comment]
Interesting catch! Thanks for reporting. We can get this patched up

**Comment by MikeKoval** [comment]
Bumped into the same....

**Comment by radiovisual** [comment]
The fix for this is now included in version `3.1.5`
