### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by ArnasDickus** [radiovisual/get-video-id#42]
**Is your feature request related to a problem? Please describe.**
When using typescript with react. I receive an error npm install @types/get-video-id. However, @types/get-video-id does not exist.

**Describe the solution you'd like**
I want to write npm install @types/get-video-id and fix this error.

**Describe alternatives you've considered**
Alternative would be is to like error suggested create declaration myself. 

**Additional context**
![image](https://user-images.githubusercontent.com/38657595/102231488-b2593600-3ef6-11eb-80ec-d4b5c45302dd.png)

**Comment by renarsvilnis** [comment]
Alternative (imo better solution, less dependencies and always in sync) can simply add an `index.d.ts` file with the types just for the public API which is very small and add `types` field in package.json.

```
  "main": "./index.js",
  "types": "./index.d.ts"
```

See guide: 
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by eugenedw** [comment]
Manually incorporated change made by @renarsvilnis - works perfect. For an Angular 11 project, the following was added to an existing module:

`import * as getVideoId from "get-video-id";`

Later, when executing, the following was used:

`let videoData = getVideoId.default(url);`

Result was in format:

```
{
  id: "h3jcmFNxRzQ"
  service: "youtube"
}
```

Great work.

**Comment by radiovisual** [comment]
@ArnasDickus @eugenedw @renarsvilnis Typescript types were added and published in get-video-id version `3.1.6`. Please update the package in your projects and you should be good to go. Happy coding!

**Comment by eugenedw** [comment]
Thanks @radiovisual - oddly enough, though, when 3.1.6 is retrieved from npmjs central - 
`https://registry.npmjs.org/get-video-id/-/get-video-id-3.1.6.tgz`
<img width="600" alt="Screen Shot 2021-01-18 at 3 00 25 AM" src="https://user-images.githubusercontent.com/2001665/104906473-98b56f00-5938-11eb-8558-706823c8fcb1.png">
the index.d.ts file is missing. The types definition in the package.json is correct, however.

**Comment by radiovisual** [comment]
Yup, I see now that the types file is missing in the `files` field of the package.json, which means it won't be bundled when the package is published.
