### ISSUE TITLE
Does not detect Vimeo recurring events

### ISSUE THREAD

**Issue by wchest** [radiovisual/get-video-id#69]
**Describe the bug**  
When passing in a Vimeo recurring event url, the service is accurately identified, but the id is not.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Call `getVideoId` with the url string: https://vimeo.com/event/1234567
2. The video information returned looks like: 
```js
{
  service: "vimeo",
  id: undefined
}
```

**Expected behavior**  
I would have expected the information returned to look like:
```js
{
  service: "vimeo",
  id: "1234567"
```
**Environment**  
This is happening client side in a browser.

**Module version**  
Using v3.1.4

**Comment by radiovisual** [comment]
Thanks for reporting this @wchest! I fixed this, and will get it published in the next version.

**Comment by wchest** [comment]
Amazing @radiovisual ! Really appreciate the quick turnaround. Thank you for all your work on this library.
