### ISSUE TITLE
Vimeo has a new ID format that contains a / and extra characters

### ISSUE THREAD

**Issue by TimothyLuke** [radiovisual/get-video-id#78]
**Describe the bug**  
Vimeo url's used to be `https://vimeo.com/320072078` where the id was `320072078`.  There are now URLs in the wild for Vimeo that contain a \ and further characters eg `https://vimeo.com/616279473/dee1f2b438` where the key is `616279473/dee1f2b438`  The vimeo function only returns the `616279473`

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Call `getVideoId` with the url string: 'https://vimeo.com/616279473/dee1f2b438'
2. you will received `{ id: '616279473', service: 'vimeo' }`

**Expected behavior**  
```{ id: '616279473', service: 'vimeo', hash: 'dee1f2b438' }```

**Environment**  
Node.js, browser

**Module version**  
get-video-id@3.4.1

**Comment by TimothyLuke** [comment]
The second parameter is a hash - ie id is `616279473` hash is `dee1f2b438`

**Comment by TimothyLuke** [comment]
The players that i tried returned a 404 with the raw URL.  This is a vimeo thing whereby their site handles this “share link” but it’s not a directly playable URL.  We had to supply the hash as a parameter to the player.  Was also able to verify issuing a HTML 5 video tag.  The hash had to be a parameter.  

Timothy Minahan
M 0406 413 680  |  E ***@***.***

**Comment by demedos** [comment]
@radiovisual An idea is having an extraData property containing the information that has been discarded from the id retrieval, like so
```
{
  service: 'vimeo',
  id: '1234',
  extraData: ['aabbcc']
},
{
  service: 'youtube',
  id: '1234',
  extraData: ['t=529', 'ab_channel=abcd']
}
```

but as you said, this is probably out of scope and would become messy and hard to maintain.
Adding an example code in the README to cover that specific use case sounds good to me.

**Comment by demedos** [comment]
@radiovisual I agree that extracting properties with specific meaning for each platform is probably out of scope and would become messy and hard to maintain quickly.
Adding an example code in the README to cover that specific use case sounds good to me.

**Comment by radiovisual** [comment]
README was updated with a note about this special format via https://github.com/radiovisual/get-video-id/pull/84. I forgot to add in an example code snippet though, so I will do that in a new PR.
