### ISSUE TITLE
Support for YouTube Shorts URLs

### ISSUE THREAD

**Issue by ipmanlk** [radiovisual/get-video-id#83]
**Is your feature request related to a problem? Please describe.**
This library fails to extract IDs from YouTube Shorts URLs.

**Describe the solution you'd like**
Add support for existing YouTube module to extract IDs from URLs similar to:  ``https://www.youtube.com/shorts/ElqDbiWidnk``.

**Comment by radiovisual** [comment]
Thanks for reporting. This feature will be published via `v3.5.3`
